### ISSUE TITLE
Language filter unable show japanese and chinese streams only

### ISSUE THREAD

**Issue by Ninmi** [vinszent/gnome-twitch#317] opened 2017-10-15 02:47 UTC
Hey, the title basically tells you most of the story. Interestingly, all other east asian languages seem to filter fine, but not japanese and chinese. Furthermore, japanese streams _do_ appear in the stream list with no filter applied, but nothing appears with a filter.
 
Apologies in advance as I don't really know what information is needed for a bug report, but I'm running Arch Linux, and Gnome Twitch is installed via AUR today.

**Comment by vinszent** [comment] 2017-10-18 12:41
Yes I can confirm this, will investigate what the issue is.

**Comment by vinszent** [comment] 2017-10-27 22:45
Ok, I've managed to get it working for Japanese streams (I had the wrong locale code), but Chinese streams are bugged on Twitch's side. I'll be migrating to the new API soon so hopefully they've fixed it there.

**Comment by Ninmi** [comment] 2017-10-30 09:03
Nice! Eager to try once the AUR package gets updated.

**Comment by vinszent** [comment] 2017-11-01 19:52
Should be fixed now, try updating the AUR package and let me know!

**Closed** 2017-11-01 19:52 UTC
Labels: bug, confirmed

**Comment by Ninmi** [comment] 2017-11-14 19:07
Switched over to the gnome-twitch-git package and the problem is now gone, thank you!

**Comment by epistularum** [comment] 2018-08-27 10:46
Issue still present in Linux mint

**Comment by vinszent** [comment] 2018-09-19 08:47
@epistularum Please ask the maintainers of that GNOME Twitch package to update it.
