### ISSUE TITLE
Language Selection

### ISSUE THREAD

**Issue by lunixer** [vinszent/gnome-twitch#228] opened 2017-02-18 11:36 UTC
Hi,

would be create if you can add an option in settings to display only channels (games) in given language.

**Comment by TingPing** [comment] 2017-02-18 18:29
Duplicate of #219

**Comment by vinszent** [comment] 2017-02-19 20:12
Currently working on this! As @TingPing pointed out however there is already an issue open for this so I'll close this one. Thanks for your feedback.

**Closed by vinszent** 2017-02-19 20:12 UTC
