### ISSUE TITLE
Fedora 26 Repo missing package

### ISSUE THREAD

**Issue by lucasdiedrich** [vinszent/gnome-twitch#295] opened 2017-07-19 23:11 UTC
There is no package available using the Fedora 26 repository:

``` bash
[root@optimus ldiedrich] # dnf repolist all
Última verificação de data de vencimento de metadados: 0:05:17 atrás em qua 19 jul 2017 20:03:53 -03.
id do repo                                                                                 nome do repo                                                                                            status
adobe-linux-x86_64                                                                         Adobe Systems Incorporated                                                                              habilitado:      3
bumblebee                                                                                  bumblebee for fedora Linux 26 - x86_64 - Base                                                           habilitado:     25
bumblebee-nonfree                                                                          bumblebee nonfree for fedora Linux 26 - x86_64 - Base                                                   habilitado:     29
bumblebee-nonfree-source                                                                   bumblebee nonfree for fedora Linux 26 - x86_64 - Source                                                 desabilitado
bumblebee-source                                                                           bumblebee for fedora Linux 26 - x86_64 - Source                                                         desabilitado
*fedora                                                                                    Fedora 26 - x86_64                                                                                      habilitado: 53.912
fedora-cisco-openh264                                                                      Fedora 26 openh264 (From Cisco) - x86_64                                                                desabilitado
fedora-cisco-openh264-debuginfo                                                            Fedora 26 openh264 (From Cisco) - x86_64 - Debug                                                        desabilitado
fedora-debuginfo                                                                           Fedora 26 - x86_64 - Debug                                                                              desabilitado
fedora-source                                                                              Fedora 26 - Source                                                                                      desabilitado
fedora-spotify                                                                             negativo17 - Spotify                                                                                    habilitado:      3
fedora-spotify-source                                                                      negativo17 - Spotify - Source                                                                           desabilitado
folkswithhats                                                                              Repository for Fedy                                                                                     habilitado:     18
google-chrome                                                                              google-chrome                                                                                           habilitado:      3
ippytraxx-gnome-twitch                                                                     Copr repo for gnome-twitch owned by ippytraxx                                                           habilitado:      0
nodesource                                                                                 Node.js Packages for Fedora Linux 26 - x86_64                                                           habilitado:     25
nodesource-source                                                                          Node.js for Fedora Linux 26 - x86_64 - Source                                                           desabilitado
region51-chrome-gnome-shell                                                                Copr repo for chrome-gnome-shell owned by region51                                                      habilitado:      2
*rpmfusion-free                                                                            RPM Fusion for Fedora 26 - Free                                                                         habilitado:    536
rpmfusion-free-debuginfo                                                                   RPM Fusion for Fedora 26 - Free - Debug                                                                 desabilitado
rpmfusion-free-source                                                                      RPM Fusion for Fedora 26 - Free - Source                                                                desabilitado
*rpmfusion-free-updates                                                                    RPM Fusion for Fedora 26 - Free - Updates                                                               habilitado:     17
rpmfusion-free-updates-debuginfo                                                           RPM Fusion for Fedora 26 - Free - Updates Debug                                                         desabilitado
rpmfusion-free-updates-source                                                              RPM Fusion for Fedora 26 - Free - Updates Source                                                        desabilitado
rpmfusion-free-updates-testing                                                             RPM Fusion for Fedora 26 - Free - Test Updates                                                          desabilitado
rpmfusion-free-updates-testing-debuginfo                                                   RPM Fusion for Fedora 26 - Free - Test Updates Debug                                                    desabilitado
rpmfusion-free-updates-testing-source                                                      RPM Fusion for Fedora 26 - Free - Test Updates Source                                                   desabilitado
*rpmfusion-nonfree                                                                         RPM Fusion for Fedora 26 - Nonfree                                                                      habilitado:    202
rpmfusion-nonfree-debuginfo                                                                RPM Fusion for Fedora 26 - Nonfree - Debug                                                              desabilitado
rpmfusion-nonfree-source                                                                   RPM Fusion for Fedora 26 - Nonfree - Source                                                             desabilitado
*rpmfusion-nonfree-updates                                                                 RPM Fusion for Fedora 26 - Nonfree - Updates                                                            habilitado:      0
rpmfusion-nonfree-updates-debuginfo                                                        RPM Fusion for Fedora 26 - Nonfree - Updates Debug                                                      desabilitado
rpmfusion-nonfree-updates-source                                                           RPM Fusion for Fedora 26 - Nonfree - Updates Source                                                     desabilitado
rpmfusion-nonfree-updates-testing                                                          RPM Fusion for Fedora 26 - Nonfree - Test Updates                                                       desabilitado
rpmfusion-nonfree-updates-testing-debuginfo                                                RPM Fusion for Fedora 26 - Nonfree - Test Updates Debug                                                 desabilitado
rpmfusion-nonfree-updates-testing-source                                                   RPM Fusion for Fedora 26 - Nonfree - Test Updates Source                                                desabilitado
*updates                                                                                   Fedora 26 - x86_64 - Updates                                                                            habilitado:  3.719
updates-debuginfo                                                                          Fedora 26 - x86_64 - Updates - Debug                                                                    desabilitado
updates-source                                                                             Fedora 26 - Updates Source                                                                              desabilitado
updates-testing                                                                            Fedora 26 - x86_64 - Test Updates                                                                       desabilitado
updates-testing-debuginfo                                                                  Fedora 26 - x86_64 - Test Updates Debug                                                                 desabilitado
updates-testing-source                                                                     Fedora 26 - Test Updates Source                                                                         desabilitado
user501254-Paper                                                                           Copr repo for Paper owned by user501254                                                                 habilitado:      4
[root@optimus ldiedrich] # dnf --disablerepo="*" --enablerepo="ippytraxx-gnome-twitch" list available
Última verificação de data de vencimento de metadados: 0:13:26 atrás em qua 19 jul 2017 19:55:46 -03.

```

**Comment by TingPing** [comment] 2017-07-19 23:20
Duplicate of #223

**Closed** 2017-07-19 23:34 UTC
